Week 2: servlet messages
kevinkong03/software-product-sprint pull request #2
Opened 2022-06-13 20:52 UTC by kevinkong03

2022-06-16 17:59 UTC, rjkroege reviewed
Seems fine.

2022-06-16 18:02 UTC, rjkroege reviewed
PR seems fine but per other blither about structuring the PRs.

2022-06-16 18:02 UTC, rjkroege commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +import java.util.*;
Imports should be in some well defined order. Perhaps alphabetical.

2022-06-16 18:02 UTC, rjkroege commented on portfolio/src/main/webapp/script.js
> +/*
Better to remove commented out code. The benefit of keeping the world in `git` is that you can always inspect the old version of the file.

2022-06-20 20:09 UTC, rjkroege commented
What order am I suppose to review in?

2022-06-20 22:34 UTC, kevinkong03 commented
Not sure why force pushing added five commits instead of just one, but I think it's okay...

2022-06-24 15:43 UTC, rjkroege requested changes

2022-06-24 15:43 UTC, rjkroege commented on portfolio/src/main/webapp/script.js
> +const responseFromServer = await fetch('/hello');
You should indent this? This code is inside the { yes?

2022-06-24 19:15 UTC, rjkroege approved these changes

2022-06-24 19:16 UTC, merged